document.querySelectorAll('.reveal').forEach(el=>new IntersectionObserver(([e],o)=>{if(e.isIntersecting){e.target.classList.add('in');o.disconnect()}},{threshold:.12}).observe(el));
const data=[
['Güne Başlarken','food',[['Fahham Serpme Kahvaltı (2 Kişilik)','1500']]],
['Omlet & Sahanda Lezzetler','food',[['Mantarlı Omlet','230'],['Beyaz Peynirli Omlet','230'],['Sade Omlet','210'],['Kaşar Peynirli Omlet','240'],['Sucuklu Omlet','240'],['Kuymak','380'],['Sahanda Sucuk','205'],['Sahanda Yumurta','190'],['Sahanda Menemen','230'],['Sahanda Kaşarlı Menemen','250'],['Sahanda Sucuklu Menemen','270'],['Sahanda Sucuklu Yumurta','240'],['Sahanda Kavurmalı Yumurta','330'],['Sahanda Kıymalı Yumurta','300']]],
['Ekmek Üstü Keyfi Kahvaltı','food',[['Avokado Ve Somonlu','420'],['Roastbeef Füme Etli','460'],['Frankfurter Sosisli','450'],['Poşe Yumurtalı','390']]],
['Büyümüşte Küçülmüşlere','food',[["Kid's Çıtır Tavuk",'320'],["Kid's Hamburger",'350'],["Kid's Sosis",'330'],["Kid's Köfte",'350']]],
['Sokak Lezzetleri & Sandwich','food',[['Steak Sandwich','840'],['Tavuk Sandvich','360'],['Köfteli Sandwich','400'],['Rostbeef Sandwich','560']]],
['Atıştırmalıklar & Tostlar','food',[['Kaburga Patates Cheddar','500'],['Çıtır Kanat','460'],['Kombo Karnaval','500'],['Kalamar Tava','860'],['Mozarella Sticks','390'],['Dana Kıymalı Nachos','480'],['Trüf Yağlı Parmesanlı Parmak Patates','300'],['Parmak Patates','535'],['Çıtır Tavuk','400'],['Kavurmalı Kaşarlı Tost','410'],['Sucuklu Kaşarlı Tost','375']]],
['Makarna','food',[['Saray Mantı','380'],['Karidesli Spaghetti','440'],['Rigatoni Bolognese','430'],['Pesto Soslu Gnocchi Makarna','520'],['Fermenter Sosisli Penne','460'],['Çıtır Mantı','400'],['Kaburgalı Rigatoni','450'],['Tavuklu Fettucine','410'],['Zucchini Spaghetti','400'],['Spaghetti Bolonez','470'],['Spicy Rigatoni','400'],['Tagliatelle Pollo E Funghi','400']]],
['Pizzalar','food',[['Akdeniz Pizza','480'],['The Specai Pizza','670'],['Supreme (Karışık) Pizza','510'],['Margherita Pizza','450'],['Roastbeef Pizza','560'],['Kaburga Pizza','600'],['Dört Peynirli Pizza','510'],['De Mare Somon Füme','670'],['Funghi (Mantarlı) Pizza','480'],['Bbq Tavuklu Pizza','480'],['Frutti Di Mare (Deniz Mahsullü) Pizza','570']]],
['Salata & Bowl','food',[['Tavuk Bowl','470'],['Köfte Bowl','570'],['Somon Bowl','560'],['Fahham Salata','440'],["Rostbeef’li Sezar Salata",'450'],['Roka Salata','410'],['Wien Salata','440'],['Semizotlu Yaz Salatası','410'],['Tavuklu Sezar Salata','440'],['Yeşil Salata','410'],['Burrata Peynirli Salata','570']]],
['Wrap & Hamburger','food',[['Metrotel Spicy Cheese Burger','460'],['Trend Burger','490'],['Çıtır Tavuk Burger','430'],['Vişne & Tulum Burger','460'],['Kaburga Burger','550'],['Bonfile Wrap','620'],['Tavuk Wrap','470']]],
['Steak House','food',[['Hünkar Çökertme','900'],['Turkısh Kebab','540'],['3 Mantar Soslu Bonfile','1000'],['Sıra Bomba','680'],['Dana Antrikot','840'],['Dana Kavurma','800'],['Yoğurtlu Combo Kebab','750'],['Kuzu İncik','880'],['Soslu Misket Köfte','600'],['Ördek Sunset','1010'],['Kaşarlı Kasap Köfte','660'],['Dana Fileminyon','1000']]],
['Chicken House','food',[['Mantar Soslu Tavuk','520'],['Köri Soslu Tavuk','530'],["Tava’da Tavuk",'550'],['Patlıcan Ezmeli Piliç Şiş','490'],['Tavuk Parmigiana Schnitzel','540'],['Tavuk Saç Kavurma','500'],['Tavuk Çökertme','530'],['Cheddar Soslu Tavuk Sarma','480'],['Limon Soslu Tavuk','480'],['Chicken Schnitzel','480'],['Asya Usulü Tavuk','540'],['Mantar Soslu Çıtır Tavuk','530']]],
['Denizden','food',[["Chef’ten Levrek",'800'],['Izgara Somon Şiş','750']]],
['Tatlılar','food',[['Snickers','390'],['Çilekli Cream Puff','400'],['Fondü','420'],['Fıstıklı Hasır Künefe','400'],['Fıstıklı Burma Kadayıf','400'],['Profiterol Topları','420'],['San Sebastian Cheesecake','410'],['Çikolatalı Suffle','410'],['Tahinli Suffle','410'],['Tramisu','390'],['Frambuazlı Cheesecake','380'],['Lüx Meyve Tabağı','530'],['Antep Fıstığı','320'],['Lüx Karışık Çerez','300']]],
['Kahve & Çay','drink',[['Matcha Latte','220'],['Demleme Çay','90'],['Türk Kahvesi','140'],['Espresso','140'],['Americano','180'],['Filtre Kahve','180'],['Cappucino','200'],['Caramel Latte','220'],['Flat White','220'],['Caffe Latte','210'],['Mocha','220'],['White Chocolate Mocha','260']]],
['Sıcak İçecekler','drink',[['Süt','145'],['Ballı Süt','165'],['Ballı Muzlu Fındıklı Süt','190'],['Çilekli Süt','175'],['Çikolatalı Süt','175'],['Salep','190'],['Damla Sakızlı Salep','195'],['Bal Badem Salep','195'],['Sıcak Çikolata','180'],['Dondurmalı Sıcak Çikolata','190'],['Beyaz Sıcak Çikolata','180']]],
['Soğuk İçecekler','drink',[['Küçük Su','80'],['Büyük Su','135'],['Ayran','100'],['Naneli Ayran','110'],['Sade Soda','110'],['Meyveli Soda','115'],['Cola','140'],['Fanta','140'],['7 Up','140'],['Zafer Gazoz','140'],['Schweppes','140'],['Meyve Suyu','140'],['Lipton Ice Tea','140'],['Churchill','170'],['Portakal Suyu','245'],['Nar Suyu','245'],['Red Bull','205']]],
['Bitki Çayları','drink',[['Special Kış Çayı','260'],['Ihlamur Çayı','260'],['Papatya Çayı','260'],['Melisa Çayı','260'],['Nane Limon Çayı','260'],['Rezene Çayı','260'],['Yeşil Çay','260']]],
['Soğuk Kahveler','drink',[['Ice Latte','240'],['Ice Cookie Mocha','250'],['Ice Karamel Machiato','250'],['Frappe','240'],['Ice Mocha','240'],['Ice White Chocolate Mocha','250'],['Ice Americano','215'],['Ice Pumpkin Spice Latte','240'],['Cold Brew','200'],['Ice Vanille Latte','240'],['Ice Nuss Latte','245'],['Ice Toffee Nut Latte','250']]],
['Mocktail / Kokteyl','drink',[['Kuzu Kulağı','240'],['Sunset','280'],['Blue Diamond','280'],['Ocean Blue','280'],['Mango Breeze','280'],['Klasik Mojito','270'],['Red Line','270'],['Sex On The Beach','270'],['Pina Colada','280'],['Sunrise','290']]],
['Milkshake','drink',[['Oreo Milkshake','285'],['Çilek Milkshake','265'],['Muz Milkshake','265'],['Çikolata Milkshake','265'],['Karamel Milkshake','265'],['Coco Star Milkshake','285'],['Vanilya Milkshake','265']]],
['Smoothie','drink',[['Çilek','250'],['Muz','250'],['Mango','250'],['Şeftali','250'],['Karadut / Böğürtlen','250']]],
['Refresha','drink',[['Cool Lime','260'],['Berry Hibiscus','260']]],
['Frozen','drink',[['Mango Ananas','275'],['Nane Limon','275'],['Yeşil Elma Frozen','275'],['Karadut Frozen','275'],['Şeftali Frozen','275'],['Kavun Frozen','275'],['Limon Frozen','275'],['Karpuz Frozen','275'],['Çilek Frozen','275']]],
['Detox','drink',[['Klasik Detox','230']]],
['Limonata','drink',[['Detox Limonata','265'],['Klasik Limonata','225'],['Çilekli Limonata','235'],['Armut - Yeşil Elma Limonata','235'],['Nane-limon Limonata','235']]],
['Extralar','drink',[['Süt Potu','70'],['Limon Potu','70']]]
];
const imageMap={'Fahham Serpme Kahvaltı (2 Kişilik)':'assets/menu/breakfast.jpg','Akdeniz Pizza':'assets/menu/pizza.jpg','Metrotel Spicy Cheese Burger':'assets/menu/burger.jpg','Bonfile Wrap':'assets/menu/wrap.jpg'};
const cats=document.querySelector('#categories'),list=document.querySelector('#menuList'),search=document.querySelector('#search');
if(cats&&list){cats.innerHTML='<button class="active" data-filter="all">Tümü</button>'+data.map((x,i)=>'<button data-filter="'+i+'">'+x[0]+'</button>').join('');list.innerHTML=data.map((x,i)=>'<section class="menu-category" data-cat="'+i+'"><div class="cat-title"><span>'+String(i+1).padStart(2,'0')+'</span><h2>'+x[0]+'</h2></div>'+x[2].map(p=>'<article class="menu-item">'+(imageMap[p[0]]?'<img class="menu-thumb" src="'+imageMap[p[0]]+'" alt="'+p[0]+'">':'')+'<div><h3>'+p[0]+'</h3></div><b>₺'+p[1]+'</b></article>').join('')+'</section>').join('');
const buttons=cats.querySelectorAll('button'),sections=list.querySelectorAll('.menu-category');function apply(){const active=cats.querySelector('.active')?.dataset.filter||'all',q=(search?.value||'').toLocaleLowerCase('tr');sections.forEach(s=>{const catOk=active==='all'||s.dataset.cat===active;let v=0;s.querySelectorAll('.menu-item').forEach(i=>{const ok=i.textContent.toLocaleLowerCase('tr').includes(q);i.style.display=ok?'flex':'none';if(ok)v++});s.style.display=catOk&&v?'block':'none'})}buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');apply()}));search?.addEventListener('input',apply);}
